### ISSUE TITLE
add linebreak-style rule

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/eslint-config-brightspace#31]
We should enforce LF linebreaks as part of a v1.0.0 major release:
https://eslint.org/docs/rules/linebreak-style

**Comment by svanherk** [comment]
Since we're still in the `0`s, could we just do this now as a minor release?

**Comment by dlockhart** [comment]
Unfortunately semver treats `0.x` as a "major" release.

**Comment by svanherk** [comment]
Right, which I think is what we want?

**Comment by dlockhart** [comment]
Oh I see, yeah like we can treat this as a major breaking change and just do it as a minor release -- for sure.

**Comment by svanherk** [comment]
Ok cool, just ran across this looking for something else, I think I'll add this Monday

**Comment by svanherk** [comment]
Added in version `0.12.0` (https://github.com/Brightspace/eslint-config-brightspace/commit/ac027438aecf84801190491f13cc1f311a89fc47)
