### ISSUE TITLE
Consider: node.js ruleset

### ISSUE THREAD

**Issue by omsmith** [Brightspace/eslint-config-brightspace#4]
There's some consistent differences between JS in node and JS in the browser, such as ES6 support (classes, arrow functions, let/const).

Might be handy to have a brightspace/node

**Comment by dbatiste** [comment]
From a config perspective, this might be just setting the env.  Do you know if there are rules you'd want configured differently?

**Comment by omsmith** [comment]
I'm just thinking along the lines of:

For the browser, _today_, I'd want ES5 only

For node, I'd want , most of ES6 (not necessarily all, but perhaps onboarding what's stable/performant/"approved"), and following that, `prefer-const: 2` (if a variable isn't assigned to after definiation, it should be `const`). I'm sure there's more in this category.

Just sort of thinking having browser and node rulesets, and then allowing more features/rules as browser support rolls out.

(As an outdated example, for browser support, we might have a rule for browser code that blacklists `Object.keys` usage. As browser support is improved, we would remove that rule)

**Comment by dbatiste** [comment]
@omsmith : Added `node-config` and `browser-config` for v0.1.0, including the prefer-const rule per your suggestion.  Feel free to update if necessary.  :)

**Comment by omsmith** [comment]
Cool thanks - just got in the office, sorry for the lack of feedback!
